#!/usr/bin/env python
# -*- coding: utf-8 -*-

STATUS_CODE_OK                  = 'OK'
STATUS_CODE_ERR_NON_JSON_FORMAT = 'NON JSON FORMAT ERROR'
STATUS_CODE_ERR_CMD_NOT_FOUND   = 'CMD NOT FOUND ERROR'
STATUS_CODE_ERR_COMMON_FIELD    = 'COMMON FIELD ERROR'
STATUS_CODE_ERR_DATA_FIELD      = 'DATA FIELD ERROR'
STATUS_CODE_ERR_CMD_IMP         = 'CMD IMPLEMENT ERROR'
STATUS_CODE_ERR_EXCEPTION       = 'EXCEPTION ERROR'
STATUS_CODE_INVALID_USER        = 'INVALID USER'
STATUS_CODE_INVALID_PASSWORD    = 'INVALID PASSWORD'
